// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_PlayerScreen_screen_init(void)
{
    ui_PlayerScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PlayerScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SongTitle = lv_label_create(ui_PlayerScreen);
    lv_obj_set_width(ui_SongTitle, 150);
    lv_obj_set_height(ui_SongTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SongTitle, 0);
    lv_obj_set_y(ui_SongTitle, -70);
    lv_obj_set_align(ui_SongTitle, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_SongTitle, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_SongTitle, "Song Name");
    lv_obj_set_style_text_align(ui_SongTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SongTitle, &ui_font_Quadron, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Artist = lv_label_create(ui_PlayerScreen);
    lv_obj_set_width(ui_Artist, 150);
    lv_obj_set_height(ui_Artist, LV_SIZE_CONTENT);    /// -62
    lv_obj_set_x(ui_Artist, 0);
    lv_obj_set_y(ui_Artist, -45);
    lv_obj_set_align(ui_Artist, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Artist, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Artist, "Artist");
    lv_obj_set_style_text_align(ui_Artist, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Artist, &ui_font_Quadron, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aplabel = lv_label_create(ui_PlayerScreen);
    lv_obj_set_width(ui_aplabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aplabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aplabel, -25);
    lv_obj_set_y(ui_aplabel, 40);
    lv_obj_set_align(ui_aplabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aplabel, "Autoplay");
    lv_obj_set_style_text_font(ui_aplabel, &ui_font_Quadron, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_prevSong = lv_imgbtn_create(ui_PlayerScreen);
    lv_imgbtn_set_src(ui_prevSong, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1487412202, NULL);
    lv_imgbtn_set_src(ui_prevSong, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1487412202, NULL);
    lv_obj_set_width(ui_prevSong, 48);
    lv_obj_set_height(ui_prevSong, 48);
    lv_obj_set_x(ui_prevSong, -60);
    lv_obj_set_y(ui_prevSong, 0);
    lv_obj_set_align(ui_prevSong, LV_ALIGN_CENTER);

    ui_playPause = lv_imgbtn_create(ui_PlayerScreen);
    lv_imgbtn_set_src(ui_playPause, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1392977354, NULL);
    lv_imgbtn_set_src(ui_playPause, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1392977354, NULL);
    lv_imgbtn_set_src(ui_playPause, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_1013023930, NULL);
    lv_imgbtn_set_src(ui_playPause, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_1013023930, NULL);
    lv_obj_set_width(ui_playPause, 48);
    lv_obj_set_height(ui_playPause, 48);
    lv_obj_set_align(ui_playPause, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_playPause, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_playPause, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_nextSong = lv_imgbtn_create(ui_PlayerScreen);
    lv_imgbtn_set_src(ui_nextSong, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1136121667, NULL);
    lv_obj_set_width(ui_nextSong, 48);
    lv_obj_set_height(ui_nextSong, 48);
    lv_obj_set_x(ui_nextSong, 60);
    lv_obj_set_y(ui_nextSong, 0);
    lv_obj_set_align(ui_nextSong, LV_ALIGN_CENTER);

    ui_autoPlay = lv_switch_create(ui_PlayerScreen);
    lv_obj_set_width(ui_autoPlay, 50);
    lv_obj_set_height(ui_autoPlay, 25);
    lv_obj_set_x(ui_autoPlay, 47);
    lv_obj_set_y(ui_autoPlay, 40);
    lv_obj_set_align(ui_autoPlay, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_autoPlay, lv_color_hex(0xFFAA41), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_autoPlay, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_autoPlay, lv_color_hex(0xFFAA41), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_autoPlay, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_autoPlay, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_autoPlay, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Time = lv_label_create(ui_PlayerScreen);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 0);
    lv_obj_set_y(ui_Time, 75);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "");
    lv_obj_set_style_text_font(ui_Time, &ui_font_Quadron, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_PlayerScreen, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 240);
    lv_obj_set_height(ui_Spinner2, 240);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xFFAB40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner2, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_prevSong, ui_event_prevSong, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_playPause, ui_event_playPause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_nextSong, ui_event_nextSong, LV_EVENT_ALL, NULL);

}
