// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_PickerScreen
void ui_PickerScreen_screen_init(void);
lv_obj_t * ui_PickerScreen;
lv_obj_t * ui_Label1;
lv_obj_t * ui_songList;
void ui_event_startPlay(lv_event_t * e);
lv_obj_t * ui_startPlay;

// SCREEN: ui_PlayerScreen
void ui_PlayerScreen_screen_init(void);
lv_obj_t * ui_PlayerScreen;
lv_obj_t * ui_SongTitle;
lv_obj_t * ui_Artist;
lv_obj_t * ui_aplabel;
void ui_event_prevSong(lv_event_t * e);
lv_obj_t * ui_prevSong;
void ui_event_playPause(lv_event_t * e);
lv_obj_t * ui_playPause;
void ui_event_nextSong(lv_event_t * e);
lv_obj_t * ui_nextSong;
lv_obj_t * ui_autoPlay;
lv_obj_t * ui_Time;
lv_obj_t * ui_Spinner2;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1397601869[1] = {&ui_img_1136121667};
const lv_img_dsc_t * ui_imgset_313891012[1] = {&ui_img_1392977354};
const lv_img_dsc_t * ui_imgset_192292922[1] = {&ui_img_1487412202};
const lv_img_dsc_t * ui_imgset_1411233666[1] = {&ui_img_11094916};
const lv_img_dsc_t * ui_imgset_1794668238[1] = {&ui_img_1013023930};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_startPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        play_selected(e);
        _ui_screen_change(ui_PlayerScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 250, 0);
    }
}
void ui_event_prevSong(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        play_prevSong(e);
    }
}
void ui_event_playPause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        play_pause(e);
        _ui_state_modify(ui_playPause, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        play_stop(e);
        _ui_screen_change(ui_PickerScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 250, 0);
        
    }
}
void ui_event_nextSong(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        play_next_song(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_PickerScreen_screen_init();
    ui_PlayerScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_PickerScreen);
}
