// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_PickerScreen
void ui_PickerScreen_screen_init(void);
extern lv_obj_t * ui_PickerScreen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_songList;
void ui_event_startPlay(lv_event_t * e);
extern lv_obj_t * ui_startPlay;
// SCREEN: ui_PlayerScreen
void ui_PlayerScreen_screen_init(void);
extern lv_obj_t * ui_PlayerScreen;
extern lv_obj_t * ui_SongTitle;
extern lv_obj_t * ui_Artist;
extern lv_obj_t * ui_aplabel;
void ui_event_prevSong(lv_event_t * e);
extern lv_obj_t * ui_prevSong;
void ui_event_playPause(lv_event_t * e);
extern lv_obj_t * ui_playPause;
void ui_event_nextSong(lv_event_t * e);
extern lv_obj_t * ui_nextSong;
extern lv_obj_t * ui_autoPlay;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1392977354);    // assets\icons8-play-48.png
LV_IMG_DECLARE(ui_img_1487412202);    // assets\icons8-skip-to-start-48.png
LV_IMG_DECLARE(ui_img_1013023930);    // assets\icons8-pause-48.png
LV_IMG_DECLARE(ui_img_1136121667);    // assets\icons8-end-48.png
LV_IMG_DECLARE(ui_img_11094916);    // assets\icons8-stop-48.png

LV_FONT_DECLARE(ui_font_Quadron);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
