// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void play_selected(lv_event_t * e);
void play_prevSong(lv_event_t * e);
void play_pause(lv_event_t * e);
void play_stop(lv_event_t * e);
void play_next_song(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
